-- 코드를 입력하세요
SELECT HISTORY_ID,CAR_ID,DATE_FORMAT(START_DATE,'%Y-%m-%d'),DATE_FORMAT(END_DATE,'%Y-%m-%d'),
(CASE WHEN DATEDIFF(end_date,start_date)+1 >= 30 THEN '장기 대여'
ELSE '단기 대여' END) AS RENT_TYPE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE start_date >= '2022-09-01 00:00:00' AND start_date < '2022-10-01 00:00:00'
ORDER BY history_id DESC;